export { discoverRelations, type DiscoverRequest, type DiscoverResult, type DiscoveredRelation } from "./discover";
export { generateCandidates, metadataCompatible, lexicalSimilarity, type CandidateOpts } from "./candidates";
export { classifyPair, hypothesisToClassification } from "./classify";
export { buildOptimizerCandidates, type ClassifiedCandidate } from "./toOptimizerCandidates";
export { eventFamily, predicateOf, relationKey, TEMPLATE_VERSION } from "./relationKey";
export { toObservation, buildRelationObservations, observationsForResolvedInstances, frozenResolvedInstance, type ResolvedInstance, type SettledOutcome } from "./settle";
export { pmOutcome, kalshiOutcome, pairResolvedInstances, type MarketOutcome } from "./enumerate";
export { buildSemanticScorer } from "./embed";
export { normalizePolymarketEvent, normalizeKalshiEvent } from "./normalize";
export type { NormalizedMarket, CandidatePair, PairClassification, Venue, RelationDirection } from "./types";
