import type { AssociationRelation, AssociationDirection, MechanismType, MechanismScope } from "./types";

export interface GoldRelation {
  id: string;
  domain: string;
  relationType: string;
  anchor: { title: string; eventClass: string };
  candidate: { title: string; eventClass: string };
  label: {
    relation: AssociationRelation;
    direction: Extract<AssociationDirection, "POSITIVE" | "NEGATIVE" | "AMBIGUOUS">;
    mechanismType: MechanismType;
    scope: MechanismScope;
    pGivenAnchorWins: number;
    pGivenAnchorFails: number;
    strengthBand: "strong" | "moderate" | "weak" | "none";
    counterexamples: string[];
    confidence: number;
  };
  basis: "logical" | "causal" | "historical";
  labeledBy: "opus-4.8";
  rationale: string;
}

export const RELATION_GOLD: GoldRelation[] = [
  {
    id: "logic-btc-threshold-implication",
    domain: "crypto", relationType: "logical-implication",
    anchor: { title: "Bitcoin above $100,000 in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Bitcoin above $90,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.25, strengthBand: "strong",
      counterexamples: ["price gaps from $80k to $110k without printing $90k"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Monotonic price: hitting $100k entails having hit $90k.",
  },
  {
    id: "logic-wc-mutex-france-spain",
    domain: "sports", relationType: "logical-mutex",
    anchor: { title: "France win the 2026 World Cup", eventClass: "tournament_winner" },
    candidate: { title: "Spain win the 2026 World Cup", eventClass: "tournament_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.18, strengthBand: "strong",
      counterexamples: ["tournament cancelled / shared title (effectively impossible)"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Only one nation wins; if France wins, Spain cannot.",
  },
  {
    id: "causal-spain-star-injury",
    domain: "sports", relationType: "same-entity-causal",
    anchor: { title: "Spain win the 2026 World Cup", eventClass: "tournament_winner" },
    candidate: { title: "Spain's first-choice striker ruled out injured before the final", eventClass: "player_injury" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.05, pGivenAnchorFails: 0.18, strengthBand: "moderate",
      counterexamples: ["a deep squad wins despite the injury"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Losing a key player lowers win probability, so the injury is more likely in the fail branch.",
  },
  {
    id: "neg-control-btc-vs-oscars",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Bitcoin above $100,000 in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Oppenheimer sequel wins Best Picture 2026", eventClass: "award_winner" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.1, pGivenAnchorFails: 0.1, strengthBand: "none",
      counterexamples: ["no shared driver"], confidence: 0.9 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Crypto price and an awards outcome share no mechanism; independent.",
  },
  {
    id: "neg-control-fed-vs-lakers",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Fed cuts rates at the next FOMC meeting", eventClass: "monetary_policy_decision" },
    candidate: { title: "Los Angeles Lakers win the 2026 NBA Finals", eventClass: "tournament_winner" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.12, pGivenAnchorFails: 0.12, strengthBand: "none",
      counterexamples: ["no shared driver between monetary policy and a basketball outcome"], confidence: 0.92 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A monetary-policy decision and an NBA championship share no causal pathway; independent.",
  },
  {
    id: "neg-control-trump-approval-vs-btc",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Trump approval rating above 45% on Dec 31, 2026", eventClass: "approval_rating_threshold" },
    candidate: { title: "Bitcoin above $90,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.4, pGivenAnchorFails: 0.4, strengthBand: "none",
      counterexamples: ["no reliable shared driver; any link is weak and noisy"], confidence: 0.75 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Presidential approval and a crypto price threshold have no dependable mechanism linking them; treat as independent.",
  },

  // ── logical-implication (objective conditionals; win-branch ≈ 1) ───────────
  {
    id: "logic-eth-threshold-implication",
    domain: "crypto", relationType: "logical-implication",
    anchor: { title: "Ethereum above $6,000 in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Ethereum above $4,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.35, strengthBand: "strong",
      counterexamples: ["a flash spike from $3.9k straight to $6.1k that never prints $4k (vanishingly unlikely on a continuous tape)"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Same asset, monotonic threshold: clearing $6k entails having been above $4k.",
  },
  {
    id: "logic-dem-electoral-implication",
    domain: "politics", relationType: "logical-implication",
    anchor: { title: "Democrats win 300+ electoral votes in 2028", eventClass: "election_margin_threshold" },
    candidate: { title: "Democrats win the 2028 US presidential election", eventClass: "election_winner" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.0, strengthBand: "strong",
      counterexamples: ["a 269–269 tie thrown to the House (cannot reach 300 EVs and lose the presidency simultaneously)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "270 EVs wins; 300+ EVs is strictly more than 270, so the larger threshold logically entails the win.",
  },
  {
    id: "logic-temp-record-implication",
    domain: "climate", relationType: "logical-implication",
    anchor: { title: "2026 is the hottest year on record globally", eventClass: "record_threshold" },
    candidate: { title: "2026 global average temperature exceeds the 2015–2025 mean", eventClass: "metric_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.7, strengthBand: "strong",
      counterexamples: ["a dataset-definition mismatch where 'record' and the decadal-mean baseline use different reanalysis products"], confidence: 0.95 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "The all-time record exceeds every prior year, hence necessarily exceeds the recent-decade mean; the fail branch is still high because warm-but-not-record years usually beat the decadal mean too.",
  },

  // ── logical-mutex (objective conditionals; win-branch ≈ 0) ──────────────────
  {
    id: "logic-election-mutex-trump-newsom",
    domain: "politics", relationType: "logical-mutex",
    anchor: { title: "A Republican wins the 2028 US presidential election", eventClass: "election_winner" },
    candidate: { title: "A Democrat wins the 2028 US presidential election", eventClass: "election_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.92, strengthBand: "strong",
      counterexamples: ["a third-party/independent winner makes both fail simultaneously"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "One winner per election; a Republican win precludes a Democratic win. Fail-branch is high but below 1 because an independent could win.",
  },
  {
    id: "logic-mutex-fed-hike-cut",
    domain: "macro", relationType: "logical-mutex",
    anchor: { title: "The Fed raises rates at the July 2026 FOMC meeting", eventClass: "monetary_policy_decision" },
    candidate: { title: "The Fed cuts rates at the July 2026 FOMC meeting", eventClass: "monetary_policy_decision" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "SAME_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.45, strengthBand: "strong",
      counterexamples: ["the Committee holds rates unchanged, so both a hike and a cut fail at the same meeting"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A single decision at one meeting cannot be both a hike and a cut; a hold makes both fail, so the fail branch sits well under 1.",
  },
  {
    id: "logic-mutex-oscar-bestpicture",
    domain: "entertainment", relationType: "logical-mutex",
    anchor: { title: "Film A wins Best Picture at the 2027 Oscars", eventClass: "award_winner" },
    candidate: { title: "Film B wins Best Picture at the 2027 Oscars", eventClass: "award_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.15, strengthBand: "strong",
      counterexamples: ["a tie is announced (Academy rules effectively preclude this for Best Picture)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Best Picture has exactly one winner; A winning means B cannot. Fail-branch low because B is only one of many nominees.",
  },

  // ── same-entity-causal (sign + mechanism + counterexample + honest band) ────
  {
    id: "causal-lakers-star-injury",
    domain: "sports", relationType: "same-entity-causal",
    anchor: { title: "Los Angeles Lakers win the 2026 NBA Finals", eventClass: "tournament_winner" },
    candidate: { title: "The Lakers' leading scorer misses 10+ playoff games injured", eventClass: "player_injury" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.07, pGivenAnchorFails: 0.22, strengthBand: "moderate",
      counterexamples: ["the bench overperforms and the team wins anyway despite the absence"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Losing the leading scorer for a chunk of the playoffs lowers title odds, so the injury concentrates in the fail branch (sign: negative).",
  },
  {
    id: "causal-incumbent-recession",
    domain: "politics", relationType: "same-entity-causal",
    anchor: { title: "The incumbent party retains the White House in 2028", eventClass: "election_winner" },
    candidate: { title: "The US enters a recession (two consecutive negative-GDP quarters) in 2027–2028", eventClass: "macro_recession" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.12, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["a brief early recession that recovers well before election day (1984-style), so the incumbent still wins"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Recessions hurt incumbents via economic-voting; a recession is therefore more likely in the branch where the incumbent loses (sign: negative). Timing of recovery is the main confounder, hence moderate.",
  },
  {
    id: "causal-tesla-deliveries-record",
    domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Tesla stock closes above $400 at end of 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Tesla reports a record quarterly delivery number in 2026", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["record deliveries at collapsing margins drag the stock down despite the volume beat"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Record deliveries are a fundamental tailwind that supports a higher share price, so they cluster in the win branch (sign: positive). Margins/valuation can break the link, so only moderate.",
  },

  // ── cross-entity (one entity's outcome shifts another's; sign + mechanism) ──
  {
    id: "cross-entity-opec-cut-exxon",
    domain: "commodities", relationType: "cross-entity",
    anchor: { title: "OPEC+ announces a production cut in H2 2026", eventClass: "supply_decision" },
    candidate: { title: "ExxonMobil stock closes above $130 at end of 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.35, strengthBand: "moderate",
      counterexamples: ["non-OPEC supply (US shale) floods the market and offsets the cut, so crude and Exxon fall anyway"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "An OPEC+ cut props up crude, lifting integrated-oil earnings and Exxon's stock — a cross-entity channel via the oil price (sign: positive). Offsetting supply is the key confounder.",
  },
  {
    id: "cross-entity-nvidia-tsmc",
    domain: "equities", relationType: "cross-entity",
    anchor: { title: "Nvidia reports a record data-center revenue quarter in 2026", eventClass: "earnings_metric" },
    candidate: { title: "TSMC reports year-over-year revenue growth above 25% in 2026", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["TSMC's other segments (auto, smartphone) slump enough to mask strong AI-chip demand"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Nvidia is a top TSMC customer; a record Nvidia data-center quarter means heavy leading-edge wafer orders, pulling TSMC revenue up (supplier channel, sign: positive).",
  },
  {
    id: "cross-entity-ukraine-ceasefire-defense",
    domain: "geopolitics", relationType: "cross-entity",
    anchor: { title: "A durable Russia–Ukraine ceasefire holds for 90+ days in 2026", eventClass: "conflict_resolution" },
    candidate: { title: "Lockheed Martin stock closes above $500 at end of 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.4, pGivenAnchorFails: 0.55, strengthBand: "weak",
      counterexamples: ["European rearmament and Pacific tensions keep defense backlogs full regardless of a Ukraine ceasefire"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A ceasefire trims the most visible demand catalyst for defense primes, mildly pressuring Lockheed (sign: negative) — but multi-year backlogs and other theaters dominate, so the link is weak.",
  },

  // ── macro-chain (macro variable → downstream market; sign + mechanism) ──────
  {
    id: "macro-chain-fed-cut-housing",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "The Fed cuts rates by 75+ bps cumulatively in 2026", eventClass: "monetary_policy_path" },
    candidate: { title: "US 30-year mortgage rate falls below 6% at any point in 2026", eventClass: "rate_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["term premium / MBS spreads widen so long rates stay high even as the Fed cuts the front end"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Front-end cuts pass partly into long rates and mortgage pricing, raising the chance the 30-year dips below 6% (sign: positive). The curve/spread can decouple, so moderate.",
  },
  {
    id: "macro-chain-inflation-gold",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "US CPI prints above 4% year-over-year in any month of 2026", eventClass: "inflation_threshold" },
    candidate: { title: "Gold closes above $3,000/oz at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.65, pGivenAnchorFails: 0.45, strengthBand: "weak",
      counterexamples: ["the Fed hikes aggressively into the inflation, real yields spike, and gold falls despite high CPI"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Higher inflation supports gold as an inflation hedge (sign: positive), but the dominant driver is real yields — a hawkish reaction can flip the relationship — so only weak.",
  },
  {
    id: "macro-chain-dollar-emerging",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "The US Dollar Index (DXY) rises above 110 at any point in 2026", eventClass: "fx_threshold" },
    candidate: { title: "The MSCI Emerging Markets index ends 2026 lower than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["a strong-dollar driven by US growth that simultaneously lifts EM exporters' earnings"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A strong dollar tightens EM financial conditions (dollar debt, capital outflows), raising the chance EM equities fall (anchor-true ↑ candidate-true). 'Why' the dollar is strong is the confounder.",
  },

  // ── geopolitics-commodity (conflict/supply shock → commodity price) ─────────
  {
    id: "geo-commodity-hormuz-oil",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "A military closure or blockade of the Strait of Hormuz occurs in 2026", eventClass: "supply_shock" },
    candidate: { title: "Brent crude closes above $120/bbl at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.9, pGivenAnchorFails: 0.15, strengthBand: "strong",
      counterexamples: ["a coordinated SPR release plus rapid de-escalation caps the spike below $120"], confidence: 0.8 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "~20% of seaborne oil transits Hormuz; a closure is a direct, large supply shock that almost always spikes Brent (sign: positive, strong). Reserve releases only partly offset.",
  },
  {
    id: "geo-commodity-russia-sanctions-gas",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "The EU imposes a full embargo on Russian pipeline gas in 2026", eventClass: "sanction_decision" },
    candidate: { title: "European TTF natural gas closes above €60/MWh at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.85, pGivenAnchorFails: 0.4, strengthBand: "strong",
      counterexamples: ["a mild winter plus full LNG import terminals keep storage high and prices contained"], confidence: 0.75 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Removing Russian pipeline gas tightens European supply and lifts TTF (sign: positive). Weather and LNG availability are the main offsets, but the directional push is strong.",
  },
  {
    id: "geo-commodity-blacksea-wheat",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "The Black Sea grain corridor is shut for 60+ consecutive days in 2026", eventClass: "supply_shock" },
    candidate: { title: "Chicago wheat futures close above $8.00/bushel at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.75, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["a bumper harvest in the US, EU and Australia replaces the lost Black Sea tonnage"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Ukraine/Russia are major wheat exporters; a prolonged corridor shutdown removes supply and pushes wheat up (sign: positive). Competing-region harvests can blunt it, hence moderate.",
  },

  // ── politics-sector (policy/election outcome → sector or asset) ─────────────
  {
    id: "politics-sector-gop-energy",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Republicans control both chambers of Congress after the 2026 midterms", eventClass: "election_winner" },
    candidate: { title: "The S&P 500 Energy sector (XLE) ends 2026 higher than the broad index", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.4, strengthBand: "weak",
      counterexamples: ["a collapse in the oil price overwhelms any policy tailwind, so energy underperforms despite favorable politics"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "GOP control favors looser drilling/permitting policy that modestly supports energy names (sign: positive), but the commodity cycle dominates sector returns, so the policy signal is weak.",
  },
  {
    id: "politics-sector-dem-renewables",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Democrats win the 2028 US presidential election", eventClass: "election_winner" },
    candidate: { title: "The clean-energy ETF (ICLN) ends 2028 up more than 20%", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.45, pGivenAnchorFails: 0.25, strengthBand: "weak",
      counterexamples: ["high interest rates crush long-duration clean-energy valuations regardless of supportive policy"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Democratic control is associated with subsidies/tax credits for renewables, a tailwind for ICLN (sign: positive). Rates and subsidy timing dominate, so the relationship is weak.",
  },
  {
    id: "politics-sector-tariff-industrials",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "The US imposes new broad tariffs above 20% on Chinese goods in 2026", eventClass: "trade_policy" },
    candidate: { title: "US-listed Chinese ADRs (KWEB) end 2026 lower than they started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.65, pGivenAnchorFails: 0.45, strengthBand: "moderate",
      counterexamples: ["aggressive Chinese stimulus offsets the tariff hit and lifts the ADRs anyway"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "New broad tariffs hurt Chinese-economy-exposed equities, raising the chance KWEB falls (anchor-true ↑ candidate-true, sign: positive). Domestic stimulus is the main counterforce.",
  },

  // ── extra negative-controls (independent / AMBIGUOUS) ───────────────────────
  {
    id: "neg-control-eurovision-vs-gdp",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Sweden wins the 2026 Eurovision Song Contest", eventClass: "award_winner" },
    candidate: { title: "US Q3 2026 GDP growth exceeds 3% annualized", eventClass: "macro_metric" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.25, pGivenAnchorFails: 0.25, strengthBand: "none",
      counterexamples: ["no plausible shared driver between a song contest and US output"], confidence: 0.93 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A European song-contest result and US GDP have no mechanism linking them; independent.",
  },
  {
    id: "neg-control-superbowl-vs-btc",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "An AFC team wins Super Bowl LXI", eventClass: "tournament_winner" },
    candidate: { title: "Bitcoin above $100,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.5, pGivenAnchorFails: 0.5, strengthBand: "none",
      counterexamples: ["the 'Super Bowl indicator' is a debunked spurious correlation, not a mechanism"], confidence: 0.9 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Which conference wins the Super Bowl carries no causal information about Bitcoin's price; treat as independent.",
  },

  // ── batch 2: more coverage (≥5 per bucket where it sharpens the signal) ─────

  // logical-implication
  {
    id: "logic-sp500-threshold-implication",
    domain: "equities", relationType: "logical-implication",
    anchor: { title: "The S&P 500 closes above 7,000 at any point in 2026", eventClass: "index_threshold" },
    candidate: { title: "The S&P 500 closes above 6,500 at any point in 2026", eventClass: "index_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.55, strengthBand: "strong",
      counterexamples: ["an overnight gap open from 6,400 straight through 7,000 that never closes at 6,500 (rare on daily-close resolution)"], confidence: 0.96 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Same index, nested thresholds: closing above 7,000 entails the index has been above 6,500. Fail-branch high because 6,500 is reachable without 7,000.",
  },
  {
    id: "logic-gop-senate-seats-implication",
    domain: "politics", relationType: "logical-implication",
    anchor: { title: "Republicans hold 55+ Senate seats after the 2026 midterms", eventClass: "election_margin_threshold" },
    candidate: { title: "Republicans hold a Senate majority after the 2026 midterms", eventClass: "election_winner" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.4, strengthBand: "strong",
      counterexamples: ["redefinition of 'majority' via an independent caucusing arrangement (does not change the 55>50 arithmetic)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "55 seats exceeds the 51 needed for a majority, so the larger count logically entails the majority.",
  },

  // logical-mutex
  {
    id: "logic-mutex-recession-no-recession",
    domain: "macro", relationType: "logical-mutex",
    anchor: { title: "The US is officially in recession (NBER) for all of Q2 2026", eventClass: "macro_recession" },
    candidate: { title: "US real GDP grows in Q2 2026", eventClass: "macro_metric" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "SAME_ENTITY",
      pGivenAnchorWins: 0.05, pGivenAnchorFails: 0.7, strengthBand: "strong",
      counterexamples: ["a quarter with positive headline GDP that NBER still dates as recessionary on employment/income (definitional edge case)"], confidence: 0.9 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A full quarter of recession and positive same-quarter growth are near-mutually-exclusive; small residual because NBER dating is multi-indicator, not GDP-only.",
  },
  {
    id: "logic-mutex-champion-relegated",
    domain: "sports", relationType: "logical-mutex",
    anchor: { title: "Manchester City win the 2026–27 Premier League title", eventClass: "tournament_winner" },
    candidate: { title: "Manchester City are relegated from the Premier League in 2026–27", eventClass: "league_outcome" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "SAME_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.05, strengthBand: "strong",
      counterexamples: ["a mid-season points deduction theoretically separating on-pitch finish from final standing (cannot make a champion finish bottom three)"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A team cannot both finish 1st and finish in the relegation zone in the same season; finishing positions are a single total order.",
  },

  // same-entity-causal
  {
    id: "causal-airline-fuel-margin",
    domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Delta Air Lines reports a record annual profit for 2026", eventClass: "earnings_metric" },
    candidate: { title: "The average jet-fuel price in 2026 is higher than in 2025", eventClass: "input_cost" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.3, pGivenAnchorFails: 0.5, strengthBand: "moderate",
      counterexamples: ["strong fare/demand pricing power lets Delta post record profit even with fuel up (hedging + capacity discipline)"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Fuel is a top airline cost; higher fuel pressures margins, so record profit is less likely when fuel rises (sign: negative). Pricing power and hedges weaken the link.",
  },
  {
    id: "causal-streamer-subs-stock",
    domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Netflix stock closes at an all-time high in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Netflix adds 30M+ net new subscribers in 2026", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.25, strengthBand: "moderate",
      counterexamples: ["the market rewards ARPU/ads monetization over raw sub growth, so the stock peaks on a softer add number"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Strong subscriber growth is a fundamental driver of Netflix's valuation, so a big add number clusters with the all-time-high branch (sign: positive). Monetization mix can substitute for raw adds.",
  },

  // cross-entity
  {
    id: "cross-entity-apple-iphone-tsmc",
    domain: "equities", relationType: "cross-entity",
    anchor: { title: "Apple reports record iPhone unit shipments for the 2026 holiday quarter", eventClass: "earnings_metric" },
    candidate: { title: "TSMC reports record advanced-node (3nm/2nm) revenue in early 2027", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.65, pGivenAnchorFails: 0.45, strengthBand: "moderate",
      counterexamples: ["Apple front-loaded wafer orders in a prior quarter, decoupling the holiday-quarter shipment from TSMC's reported timing"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Apple is TSMC's largest leading-edge customer; a record iPhone quarter implies heavy advanced-node demand, lifting TSMC (supplier channel, sign: positive). Order-timing lag is the confounder.",
  },
  {
    id: "cross-entity-saudi-aramco-tax",
    domain: "geopolitics", relationType: "cross-entity",
    anchor: { title: "Saudi Arabia commits to extended deep OPEC+ output cuts through 2027", eventClass: "supply_decision" },
    candidate: { title: "US shale producer Diamondback Energy raises its 2027 capex guidance", eventClass: "corporate_guidance" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.35, strengthBand: "weak",
      counterexamples: ["US shale stays disciplined on capital returns and keeps capex flat despite higher prices"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Saudi cuts support crude, improving US shale economics and inviting more capex — a cross-entity price channel (sign: positive). Capital-discipline norms make it weak.",
  },

  // macro-chain
  {
    id: "macro-chain-rate-cut-regional-banks",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "The Fed cuts rates at three or more meetings in 2026", eventClass: "monetary_policy_path" },
    candidate: { title: "The regional-bank ETF (KRE) ends 2026 higher than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "weak",
      counterexamples: ["cuts come because of a recession that drives loan losses, so regional banks fall even as the Fed eases"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Cuts relieve funding costs and CRE stress for regional banks (sign: positive), but if cuts are recession-driven, credit losses dominate — a classic 'why are they cutting' confounder, hence weak.",
  },
  {
    id: "macro-chain-oil-airlines",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "WTI crude averages above $90/bbl over 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "The US airline ETF (JETS) ends 2026 lower than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["robust travel demand lets carriers pass fuel costs into fares, so JETS rises despite expensive oil"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Sustained high oil raises airlines' largest variable cost, pressuring the group (anchor-true ↑ candidate-true, sign: positive). Demand-driven pricing power is the offset.",
  },

  // geopolitics-commodity
  {
    id: "geo-commodity-taiwan-tensions-chips",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "China imposes a naval quarantine or blockade around Taiwan in 2026", eventClass: "supply_shock" },
    candidate: { title: "Spot DRAM/NAND memory contract prices rise more than 30% within a quarter in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.85, pGivenAnchorFails: 0.2, strengthBand: "strong",
      counterexamples: ["a glut of existing memory inventory cushions the immediate price reaction"], confidence: 0.75 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A Taiwan blockade threatens the world's leading-edge logic and feeds memory-supply panic; semiconductor prices spike (sign: positive, strong). Inventory buffers only partly absorb the shock.",
  },
  {
    id: "geo-commodity-congo-cobalt",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "An export ban or major conflict disrupts DRC cobalt mining for 30+ days in 2026", eventClass: "supply_shock" },
    candidate: { title: "Cobalt prices rise above $40,000/tonne at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.8, pGivenAnchorFails: 0.25, strengthBand: "strong",
      counterexamples: ["weak EV-battery demand and Indonesian nickel-cobalt substitution cap the price despite the DRC disruption"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "The DRC supplies the majority of mined cobalt; a sustained disruption is a direct supply shock that lifts cobalt (sign: positive). Demand softness and substitutes can blunt it.",
  },

  // politics-sector
  {
    id: "politics-sector-drug-pricing-pharma",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Congress passes expanded Medicare drug-price negotiation in 2026", eventClass: "legislation" },
    candidate: { title: "The S&P pharma sub-industry underperforms the S&P 500 over the following quarter", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["the bill is milder than feared and triggers a relief rally in pharma"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Expanded price negotiation compresses pharma pricing power, pressuring the group relative to the market (anchor-true ↑ candidate-true, sign: positive). 'Better than feared' outcomes are the main risk to the sign.",
  },
  {
    id: "politics-sector-defense-budget",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Congress enacts a defense budget above $950B for FY2027", eventClass: "legislation" },
    candidate: { title: "The aerospace & defense ETF (ITA) outperforms the S&P 500 over the following two quarters", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.4, strengthBand: "weak",
      counterexamples: ["the budget is already priced in, so the enactment is a 'sell-the-news' event for defense names"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A larger defense budget supports prime-contractor backlogs and defense equities (sign: positive), but expectations are usually pre-positioned, so the realized relative move is weak.",
  },
  {
    id: "logic-impl-cl-final-semifinal", domain: "sports", relationType: "logical-implication",
    anchor: { title: "Real Madrid reach the 2026 Champions League final", eventClass: "tournament_stage" },
    candidate: { title: "Real Madrid reach the 2026 Champions League semifinal", eventClass: "tournament_stage" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1, pGivenAnchorFails: 0.18, strengthBand: "strong",
      counterexamples: ["a bracket reform that seeds finalists directly past the semifinal round (not how the current format works)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Stage progression is nested: a team can only reach the final by first winning its semifinal, so reaching the final entails reaching the semifinal.",
  },
  {
    id: "logic-impl-cpi-threshold-ladder", domain: "macro", relationType: "logical-implication",
    anchor: { title: "US year-over-year CPI inflation exceeds 4% in any month of 2026", eventClass: "inflation_threshold" },
    candidate: { title: "US year-over-year CPI inflation exceeds 3% in any month of 2026", eventClass: "inflation_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1, pGivenAnchorFails: 0.55, strengthBand: "strong",
      counterexamples: ["a BLS index rebasing that uses a different reference series for the two markets (definitional edge case, not the arithmetic)"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Nested numeric thresholds on the same metric: any month above 4% is necessarily above 3%; fail-branch stays high because 3% is reachable without 4%.",
  },
  {
    id: "logic-impl-vote-share-ladder", domain: "politics", relationType: "logical-implication",
    anchor: { title: "The AfD wins over 25% of the vote in the next German federal election", eventClass: "vote_share_threshold" },
    candidate: { title: "The AfD wins over 20% of the vote in the next German federal election", eventClass: "vote_share_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1, pGivenAnchorFails: 0.45, strengthBand: "strong",
      counterexamples: ["a market that resolves on second-vote (Zweitstimme) versus first-vote share, splitting the denominator (definitional, not arithmetic)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Same party, same election, nested vote-share ladder: clearing 25% logically entails clearing 20%; fail-branch high because 20% is attainable without 25%.",
  },
  {
    id: "logic-impl-nfl-win-total", domain: "sports", relationType: "logical-implication",
    anchor: { title: "The Kansas City Chiefs win 13+ games in the 2026 NFL regular season", eventClass: "win_total_threshold" },
    candidate: { title: "The Kansas City Chiefs win 11+ games in the 2026 NFL regular season", eventClass: "win_total_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1, pGivenAnchorFails: 0.35, strengthBand: "strong",
      counterexamples: ["a season-length change or forfeit-counting rule that alters how wins are tallied for one market (definitional, not the count itself)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Nested win-total thresholds for one team in one season: 13+ wins necessarily includes 11+ wins; fail-branch moderate since 11-12 wins clear the lower bar without the higher.",
  },
  {
    id: "logic-impl-marathon-record-time", domain: "sports", relationType: "logical-implication",
    anchor: { title: "The men's marathon world record falls below 2:00:00 in 2026", eventClass: "record_time_threshold" },
    candidate: { title: "The men's marathon world record falls below 2:01:00 in 2026", eventClass: "record_time_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1, pGivenAnchorFails: 0.3, strengthBand: "strong",
      counterexamples: ["a ratification dispute where World Athletics certifies the sub-2:01 mark but not the sub-2:00 mark on a technicality (definitional edge case)"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Faster nested time thresholds: a record under 2:00:00 is necessarily under 2:01:00; fail-branch moderate because a sub-2:01 record can be set without breaking 2:00.",
  },
  {
    id: "logic-impl-box-office-gross", domain: "entertainment", relationType: "logical-implication",
    anchor: { title: "Avatar 3 grosses over $2 billion worldwide", eventClass: "box_office_threshold" },
    candidate: { title: "Avatar 3 grosses over $1.5 billion worldwide", eventClass: "box_office_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1, pGivenAnchorFails: 0.4, strengthBand: "strong",
      counterexamples: ["one market counting only theatrical gross while the other includes re-release revenue (definitional difference, not the cumulative total)"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Cumulative worldwide gross is monotonic: passing $2B entails having passed $1.5B; fail-branch moderate because $1.5B is reachable without reaching $2B.",
  },
  {
    id: "logic-impl-temp-record-warmest-decade", domain: "climate", relationType: "logical-implication",
    anchor: { title: "London records its hottest day ever in summer 2026", eventClass: "record_threshold" },
    candidate: { title: "London records a daily high above 38C in summer 2026", eventClass: "metric_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1, pGivenAnchorFails: 0.2, strengthBand: "strong",
      counterexamples: ["a station-relocation or dataset-source mismatch where 'hottest ever' uses a different official station than the 38C market (definitional edge case)"], confidence: 0.95 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "London's existing all-time record exceeds 38C, so a new hottest-ever day necessarily clears 38C; fail-branch low because a 38C-plus day need not be all-time hottest.",
  },
  {
    id: "logic-mutex-gop-primary-desantis-haley", domain: "politics", relationType: "logical-mutex",
    anchor: { title: "Ron DeSantis wins the 2028 Republican presidential nomination", eventClass: "primary_winner" },
    candidate: { title: "Nikki Haley wins the 2028 Republican presidential nomination", eventClass: "primary_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0, pGivenAnchorFails: 0.22, strengthBand: "strong",
      counterexamples: ["a brokered convention that somehow seats two nominees (impossible under party rules)"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Exactly one candidate wins a single party's nomination; if DeSantis wins, Haley cannot. Fail-branch moderate because Haley is one of several contenders.",
  },
  {
    id: "logic-mutex-ucl-final-realmadrid-bayern", domain: "sports", relationType: "logical-mutex",
    anchor: { title: "Real Madrid win the 2026-27 UEFA Champions League", eventClass: "tournament_winner" },
    candidate: { title: "Bayern Munich win the 2026-27 UEFA Champions League", eventClass: "tournament_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0, pGivenAnchorFails: 0.16, strengthBand: "strong",
      counterexamples: ["the final is abandoned and the title shared (UEFA rules force a single winner via penalties)"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Only one club lifts the trophy; Real Madrid winning precludes Bayern winning. Fail-branch low because Bayern is one of many entrants.",
  },
  {
    id: "logic-mutex-conclave-pope-two-cardinals", domain: "world", relationType: "logical-mutex",
    anchor: { title: "Cardinal Pietro Parolin is elected the next Pope", eventClass: "office_succession" },
    candidate: { title: "Cardinal Luis Antonio Tagle is elected the next Pope", eventClass: "office_succession" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0, pGivenAnchorFails: 0.12, strengthBand: "strong",
      counterexamples: ["a schism produces two rival claimants (canonically only one valid election occurs)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A conclave elects exactly one Pope; if Parolin is chosen, Tagle cannot be. Fail-branch low because Tagle is one of many papabili.",
  },
  {
    id: "logic-mutex-host-city-paris-madrid", domain: "world", relationType: "logical-mutex",
    anchor: { title: "Brisbane is chosen to host a future Summer Olympics edition awarded in 2026", eventClass: "host_selection" },
    candidate: { title: "Doha is chosen to host that same future Summer Olympics edition awarded in 2026", eventClass: "host_selection" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0, pGivenAnchorFails: 0.3, strengthBand: "strong",
      counterexamples: ["the IOC awards a rare joint/co-host arrangement spanning both cities"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A single Olympic edition is awarded to one host; Brisbane winning the bid precludes Doha for that edition. Fail-branch moderate because several cities compete.",
  },
  {
    id: "logic-mutex-fight-outcome-ko-decision", domain: "sports", relationType: "logical-mutex",
    anchor: { title: "The 2026 undisputed heavyweight title fight ends by knockout or TKO", eventClass: "contest_outcome" },
    candidate: { title: "The 2026 undisputed heavyweight title fight ends by judges' decision (goes the distance)", eventClass: "contest_outcome" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "SAME_ENTITY",
      pGivenAnchorWins: 0, pGivenAnchorFails: 0.65, strengthBand: "strong",
      counterexamples: ["the bout ends in disqualification or no-contest, making both the KO and the decision outcomes fail"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A single fight cannot both end inside the distance by stoppage and go to a full decision; a DQ/no-contest makes both fail, so the fail branch is below 1.",
  },
  {
    id: "logic-mutex-coin-flip-toss-heads-tails", domain: "crypto", relationType: "logical-mutex",
    anchor: { title: "Solana flips Ethereum by total market cap at any point in 2026", eventClass: "ranking_flip" },
    candidate: { title: "Ethereum flips Bitcoin by total market cap at any point in 2026", eventClass: "ranking_flip" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.02, pGivenAnchorFails: 0.1, strengthBand: "moderate",
      counterexamples: ["a wild rotation where ETH briefly tops BTC and later SOL tops ETH within the same year, satisfying both"], confidence: 0.82 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "If Solana overtakes Ethereum in cap, Ethereum is not simultaneously overtaking Bitcoin from the #2 slot; the two ordering claims conflict for almost any single snapshot, so the win branch sits near zero while the fail branch is low.",
  },
  {
    id: "logic-mutex-cfp-champion-bama-uga", domain: "sports", relationType: "logical-mutex",
    anchor: { title: "Ohio State win the 2026-27 College Football Playoff national championship", eventClass: "tournament_winner" },
    candidate: { title: "Georgia win the 2026-27 College Football Playoff national championship", eventClass: "tournament_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0, pGivenAnchorFails: 0.2, strengthBand: "strong",
      counterexamples: ["the title game is vacated after the fact (does not let two teams hold the championship at once)"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "The CFP crowns a single national champion; Ohio State winning means Georgia cannot. Fail-branch moderate because Georgia is one of several contenders.",
  },
  {
    id: "causal-se-manager-sacked-top4", domain: "sports", relationType: "same-entity-causal",
    anchor: { title: "Tottenham Hotspur finish in the Premier League top 4 in the 2026-27 season", eventClass: "league_finish_position" },
    candidate: { title: "Tottenham Hotspur sack their head coach mid-season (2026-27)", eventClass: "manager_dismissal" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.08, pGivenAnchorFails: 0.32, strengthBand: "moderate",
      counterexamples: ["a mid-season managerial change sparks a turnaround and the new boss drags the club into the top 4 anyway"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A mid-season sacking signals poor form and disrupts the squad, lowering top-4 odds, so it concentrates in the fail branch (sign: negative).",
  },
  {
    id: "causal-se-qb-injury-superbowl", domain: "sports", relationType: "same-entity-causal",
    anchor: { title: "The Kansas City Chiefs win Super Bowl LXI (2026 season)", eventClass: "tournament_winner" },
    candidate: { title: "The Chiefs' starting quarterback misses 4+ regular-season games with injury (2026 season)", eventClass: "player_injury" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.06, pGivenAnchorFails: 0.2, strengthBand: "moderate",
      counterexamples: ["the backup plays well, the team secures a bye, and the star returns fresh to win it all"], confidence: 0.68 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A franchise QB missing multiple games hurts seeding and title odds, so the injury clusters in the fail branch (sign: negative).",
  },
  {
    id: "causal-se-biotech-fda-approval", domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Moderna stock closes above $60 at the end of 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "The FDA grants approval to a key Moderna pipeline candidate in 2026", eventClass: "regulatory_approval" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.28, strengthBand: "moderate",
      counterexamples: ["the approval lands but with a narrow label and weak launch, so the stock fails to clear the threshold despite the catalyst"], confidence: 0.62 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A pipeline approval is a fundamental value catalyst that supports a higher share price, so it clusters in the win branch (sign: positive).",
  },
  {
    id: "causal-se-ceo-ouster-all=time-high", domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Boeing stock closes at an all-time high in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Boeing's CEO is ousted or resigns under pressure in 2026", eventClass: "executive_departure" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.07, pGivenAnchorFails: 0.24, strengthBand: "moderate",
      counterexamples: ["the market cheers a forced CEO exit as a turnaround signal and the stock rallies to a new high on the change"], confidence: 0.62 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A pressured CEO departure usually reflects operational or crisis trouble that depresses the stock, so it concentrates in the fail branch (sign: negative).",
  },
  {
    id: "causal-se-data-breach-record-revenue", domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Equifax reports record annual revenue for fiscal 2026", eventClass: "earnings_metric" },
    candidate: { title: "Equifax discloses a major customer data breach in 2026", eventClass: "security_incident" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.08, pGivenAnchorFails: 0.18, strengthBand: "weak",
      counterexamples: ["a breach is disclosed but contained quickly, and strong underlying demand still drives record revenue that year"], confidence: 0.55 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A major breach triggers churn, remediation cost, and reputational damage that pressure revenue, so it leans into the fail branch (sign: negative).",
  },
  {
    id: "causal-se-drought-hydro-power", domain: "commodities", relationType: "same-entity-causal",
    anchor: { title: "Brazil's national hydroelectric output sets a record high in 2026", eventClass: "production_volume" },
    candidate: { title: "Brazil experiences a severe multi-region drought during 2026", eventClass: "weather_event" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.05, pGivenAnchorFails: 0.27, strengthBand: "strong",
      counterexamples: ["drought hits late in the year after reservoirs were already full from a wet first half, so annual output still sets a record"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Hydro output depends directly on reservoir levels; a severe drought drains them and suppresses generation, so it concentrates in the fail branch (sign: negative).",
  },
  {
    id: "causal-se-strong-jobs-incumbent-governor", domain: "politics", relationType: "same-entity-causal",
    anchor: { title: "The incumbent governor of California wins re-election in 2026", eventClass: "election_winner" },
    candidate: { title: "California's unemployment rate falls below 4% during 2026", eventClass: "macro_indicator" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "BEHAVIORAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.42, pGivenAnchorFails: 0.24, strengthBand: "moderate",
      counterexamples: ["a low jobless rate coincides with a cost-of-living backlash that sinks the incumbent despite strong employment"], confidence: 0.58 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A strong local labor market boosts incumbent approval via economic voting, so low unemployment clusters in the win branch (sign: positive).",
  },
  {
    id: "causal-se-cost-overrun-launch-success", domain: "science", relationType: "same-entity-causal",
    anchor: { title: "NASA's Artemis crewed lunar landing mission succeeds on schedule by end of 2027", eventClass: "mission_outcome" },
    candidate: { title: "The Artemis program reports a major budget overrun in 2026", eventClass: "project_cost" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "INSTITUTIONAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.2, pGivenAnchorFails: 0.42, strengthBand: "moderate",
      counterexamples: ["the overrun buys extra testing margin that actually de-risks the mission and it lands on time anyway"], confidence: 0.55 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A major budget overrun signals technical/management trouble that tends to slip schedules, so it leans into the fail branch (sign: negative).",
  },
  {
    id: "cross-ent-mbappe-real-vs-psg", domain: "sports", relationType: "cross-entity",
    anchor: { title: "Kylian Mbappé signs for Real Madrid before the 2026 summer window closes", eventClass: "player_signing" },
    candidate: { title: "Kylian Mbappé re-signs a contract extension with Paris Saint-Germain in summer 2026", eventClass: "player_signing" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.01, pGivenAnchorFails: 0.45, strengthBand: "strong",
      counterexamples: ["A short-term loan-back arrangement where the player is technically registered to both clubs in a transitional window — practically impossible for a single player's primary contract"], confidence: 0.93 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "One player can hold only one primary club contract at a time, so a Real Madrid signing precludes a PSG extension; the candidate pays far more when the anchor fails (sign: negative).",
  },
  {
    id: "cross-ent-amazon-vs-microsoft-pentagon", domain: "technology", relationType: "cross-entity",
    anchor: { title: "Amazon Web Services wins the next major U.S. DoD enterprise cloud contract awarded in 2026", eventClass: "contract_award" },
    candidate: { title: "Microsoft Azure wins the next major U.S. DoD enterprise cloud contract awarded in 2026", eventClass: "contract_award" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.03, pGivenAnchorFails: 0.4, strengthBand: "strong",
      counterexamples: ["The Pentagon splits the award into a multi-vendor structure giving both primes a share, so both 'win' simultaneously"], confidence: 0.85 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A single sole-source enterprise cloud award goes to one prime, so an AWS win blocks an Azure win on the same contract; candidate pays more when anchor fails (sign: negative).",
  },
  {
    id: "cross-ent-brisbane-vs-doha-olympics", domain: "sports", relationType: "cross-entity",
    anchor: { title: "A European/American city is selected to host the 2040 Summer Olympics", eventClass: "host_selection" },
    candidate: { title: "A Middle Eastern city is selected to host the 2040 Summer Olympics", eventClass: "host_selection" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.01, pGivenAnchorFails: 0.5, strengthBand: "strong",
      counterexamples: ["The IOC awards a co-hosting bid spanning two regions, so both region categories share the Games"], confidence: 0.9 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "The IOC selects one host for a given edition, so a Western host precludes a Middle Eastern host; the candidate pays far more when the anchor fails (sign: negative).",
  },
  {
    id: "cross-ent-boeing-vs-airbus-megaorder", domain: "aviation", relationType: "cross-entity",
    anchor: { title: "Boeing wins a flag-carrier airline's exclusive 100+ widebody fleet-renewal order announced in 2026", eventClass: "contract_award" },
    candidate: { title: "Airbus wins that same flag-carrier airline's exclusive 100+ widebody fleet-renewal order in 2026", eventClass: "contract_award" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.05, pGivenAnchorFails: 0.38, strengthBand: "strong",
      counterexamples: ["The airline deliberately dual-sources and splits the renewal order between both manufacturers despite the 'exclusive' framing"], confidence: 0.82 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "An exclusive single-OEM fleet order is awarded to one manufacturer, so a Boeing win crowds out Airbus on that order; candidate pays more when anchor fails (sign: negative).",
  },
  {
    id: "cross-ent-tesla-vs-byd-evshare", domain: "automotive", relationType: "cross-entity",
    anchor: { title: "Tesla is the #1 global battery-EV seller by units for full-year 2026", eventClass: "market_share_rank" },
    candidate: { title: "BYD is the #1 global battery-EV seller by units for full-year 2026", eventClass: "market_share_rank" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.02, pGivenAnchorFails: 0.65, strengthBand: "strong",
      counterexamples: ["A definitional dead heat where the two are tied to the unit and both are reported as co-#1 by different trackers"], confidence: 0.88 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Only one firm can hold the #1 BEV-unit rank in a year, so Tesla taking the top spot precludes BYD taking it; candidate pays far more when anchor fails (sign: negative).",
  },
  {
    id: "cross-ent-uber-vs-lyft-citylicense", domain: "technology", relationType: "cross-entity",
    anchor: { title: "Uber wins the exclusive autonomous-robotaxi operating permit for a major U.S. metro awarded in 2026", eventClass: "license_award" },
    candidate: { title: "Lyft's stock closes up more than 30% from its 2026 open by year-end", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.18, pGivenAnchorFails: 0.32, strengthBand: "moderate",
      counterexamples: ["Lyft rallies on its own AV partnerships and overall ride-hailing demand even after losing the exclusive metro permit to Uber"], confidence: 0.62 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "An exclusive robotaxi permit to Uber signals Lyft losing the highest-value autonomy beachhead, pressuring Lyft's growth narrative and stock (sign: negative); broad sector tailwinds can offset, so moderate.",
  },
  {
    id: "cross-ent-pfizer-vs-moderna-rsv", domain: "healthcare", relationType: "cross-entity",
    anchor: { title: "Pfizer captures the majority share of U.S. older-adult RSV vaccinations for the 2026–27 season", eventClass: "market_share_rank" },
    candidate: { title: "Moderna captures the majority share of U.S. older-adult RSV vaccinations for the 2026–27 season", eventClass: "market_share_rank" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.02, pGivenAnchorFails: 0.42, strengthBand: "strong",
      counterexamples: ["A third competitor (e.g., GSK) takes the majority, so neither named firm wins but they are not directly trading the same share against each other"], confidence: 0.84 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Majority share of one season's vaccinations can belong to only one supplier, so Pfizer holding it precludes Moderna holding it; candidate pays more when anchor fails (sign: negative).",
  },
  {
    id: "macro-chain-yield-mortgage", domain: "macro", relationType: "macro-chain",
    anchor: { title: "The US 10-year Treasury yield closes above 5% at any point in 2026", eventClass: "rate_threshold" },
    candidate: { title: "The US 30-year fixed mortgage rate closes above 7.5% at any point in 2026", eventClass: "rate_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.88, pGivenAnchorFails: 0.25, strengthBand: "strong",
      counterexamples: ["MBS spreads compress sharply (e.g. heavy GSE/Fed buying) so mortgage rates lag even as the 10-year tops 5%"], confidence: 0.78 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "30-year mortgages are priced as the 10-year plus a roughly stable MBS spread, so a 5%+ 10-year mechanically pushes mortgages above 7.5% (sign: positive).",
  },
  {
    id: "macro-chain-unemployment-equities", domain: "macro", relationType: "macro-chain",
    anchor: { title: "US unemployment rises above 5.5% in any month of 2026", eventClass: "labor_market_threshold" },
    candidate: { title: "The S&P 500 ends 2026 up more than 10% from its 2026 open", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.25, pGivenAnchorFails: 0.45, strengthBand: "moderate",
      counterexamples: ["rising unemployment triggers aggressive Fed easing that re-rates equities higher in a 'bad-news-is-good-news' rally"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A jump in unemployment signals weakening demand and earnings, lowering the odds of a strong double-digit equity year (sign: negative); the rate-cut offset keeps it from being strong.",
  },
  {
    id: "macro-chain-cpi-fed-hold", domain: "macro", relationType: "macro-chain",
    anchor: { title: "US core CPI stays above 3% year-over-year in every month of 2026", eventClass: "inflation_threshold" },
    candidate: { title: "The Fed holds its policy rate unchanged for the entire 2026 calendar year", eventClass: "monetary_policy_path" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.2, strengthBand: "moderate",
      counterexamples: ["a sharp growth scare forces the Fed to cut despite sticky 3%+ inflation, breaking the hold"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Persistently above-target inflation removes the Fed's room to ease and biases it toward holding (sign: positive); a recession could override the inflation signal, so moderate.",
  },
  {
    id: "macro-chain-dollar-oil", domain: "macro", relationType: "macro-chain",
    anchor: { title: "The US Dollar Index (DXY) averages above 108 over 2026", eventClass: "fx_threshold" },
    candidate: { title: "Brent crude closes above $90/bbl at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.3, pGivenAnchorFails: 0.5, strengthBand: "moderate",
      counterexamples: ["a major OPEC+ supply cut or geopolitical shock spikes Brent past $90 even while the dollar stays strong"], confidence: 0.58 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Oil is priced in dollars, so a strong dollar mechanically and through demand suppresses oil prices, lowering the chance Brent tops $90 (sign: negative); supply shocks can dominate.",
  },
  {
    id: "macro-chain-credit-spreads-hy-default", domain: "macro", relationType: "macro-chain",
    anchor: { title: "US high-yield credit spreads widen beyond 600 bps at any point in 2026", eventClass: "credit_spread_threshold" },
    candidate: { title: "The US speculative-grade corporate default rate exceeds 5% in 2026", eventClass: "default_rate_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.2, strengthBand: "strong",
      counterexamples: ["spreads widen on a liquidity/technical scare that reverses quickly without translating into actual defaults"], confidence: 0.72 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Wide HY spreads raise refinancing costs and signal market-priced distress, both of which feed realized defaults (sign: positive); spreads can overshoot fundamentals, capping certainty.",
  },
  {
    id: "macro-chain-gdp-contraction-jobless", domain: "macro", relationType: "macro-chain",
    anchor: { title: "US real GDP contracts in two consecutive quarters in 2026", eventClass: "gdp_growth_threshold" },
    candidate: { title: "US weekly initial jobless claims exceed 350k in any week of 2026", eventClass: "labor_market_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.8, pGivenAnchorFails: 0.3, strengthBand: "strong",
      counterexamples: ["a shallow, productivity-driven contraction where firms hoard labor keeps claims subdued below 350k"], confidence: 0.74 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Two quarters of output contraction typically force layoffs that lift jobless claims (sign: positive); labor-hoarding in a mild recession is the main offset, so strong but not certain.",
  },
  {
    id: "macro-chain-fed-cut-dollar-weak", domain: "macro", relationType: "macro-chain",
    anchor: { title: "The Fed cuts its policy rate by 100+ bps cumulatively in 2026", eventClass: "monetary_policy_path" },
    candidate: { title: "The US Dollar Index (DXY) ends 2026 below 100", eventClass: "fx_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["other central banks ease even faster, so relative rate differentials keep the dollar bid above 100 despite Fed cuts"], confidence: 0.62 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Falling US rates narrow yield differentials and reduce dollar carry, pushing DXY lower (sign: positive); FX is relative, so foreign easing can offset the move.",
  },
  {
    id: "geo-comm-redsea-houthi-freight", domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "Houthi attacks force a sustained 60+ day rerouting of container traffic away from the Red Sea/Suez in 2026", eventClass: "supply_shock" },
    candidate: { title: "The Shanghai Containerized Freight Index (SCFI) closes above 3,000 at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "CAUSAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.85, pGivenAnchorFails: 0.3, strengthBand: "strong",
      counterexamples: ["a glut of newbuild container capacity absorbs the longer Cape-of-Good-Hope routings and keeps spot freight rates contained"], confidence: 0.75 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Diverting Asia-Europe traffic around Africa adds ~10 days and ties up ship capacity, tightening effective supply and spiking container freight rates (sign: positive).",
  },
  {
    id: "geo-comm-niger-uranium-spot", domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "A coup or export halt disrupts Niger uranium exports for 90+ days in 2026", eventClass: "supply_shock" },
    candidate: { title: "Spot uranium (U3O8) closes above $120/lb at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "CAUSAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["utilities draw down ample inventories and Kazakh/Canadian output ramps to backfill the lost Nigerien tonnage"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Niger is a meaningful share of Western-aligned uranium supply; a prolonged halt tightens an already thin spot market and lifts U3O8 (sign: positive). Inventories and other producers blunt it.",
  },
  {
    id: "geo-comm-iran-israel-strike-gold", domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "A direct large-scale military exchange between Israel and Iran occurs in 2026", eventClass: "supply_shock" },
    candidate: { title: "Spot gold closes above $3,500/oz at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "CAUSAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.72, pGivenAnchorFails: 0.42, strengthBand: "moderate",
      counterexamples: ["a brief, contained exchange with rapid de-escalation triggers only a transient safe-haven bid that fades before gold breaches $3,500"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A major Israel-Iran conflict drives safe-haven demand and a geopolitical risk premium into gold (sign: positive). Magnitude depends on conflict duration and how high gold already sits.",
  },
  {
    id: "geo-comm-ukraine-ceasefire-wheat", domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "A durable Russia-Ukraine ceasefire holding 90+ days is reached in 2026", eventClass: "ceasefire_agreement" },
    candidate: { title: "Chicago wheat futures close above $7.50/bushel at any point after the ceasefire in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.3, pGivenAnchorFails: 0.55, strengthBand: "moderate",
      counterexamples: ["a severe drought across the US and EU breadbaskets pushes wheat above $7.50 despite restored Black Sea export flows"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A durable ceasefire restores Black Sea grain exports and removes the war risk premium, easing wheat supply and lowering prices (sign: negative). Weather shocks can override the supply relief.",
  },
  {
    id: "geo-comm-opec-surprise-hike-brent", domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "OPEC+ announces a surprise unwinding of 2M+ bpd of voluntary cuts in 2026", eventClass: "supply_decision" },
    candidate: { title: "Brent crude closes above $85/bbl at any point in the three months following the announcement", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.35, pGivenAnchorFails: 0.6, strengthBand: "moderate",
      counterexamples: ["a simultaneous supply outage elsewhere or a demand surge keeps Brent above $85 even as OPEC+ adds barrels"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A surprise return of withheld OPEC+ barrels loosens the oil balance and pressures Brent lower (sign: negative). Offsetting outages or strong demand can keep prices elevated.",
  },
  {
    id: "geo-comm-indonesia-nickel-ban", domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "Indonesia imposes new export restrictions on processed nickel products in 2026", eventClass: "export_restriction" },
    candidate: { title: "LME nickel closes above $20,000/tonne at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "CAUSAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.35, strengthBand: "moderate",
      counterexamples: ["a large existing global nickel surplus and weak stainless/EV demand absorb the restriction and cap the price below $20,000"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Indonesia dominates global nickel supply; new export curbs tighten availability and lift LME nickel (sign: positive). A standing surplus and soft demand are the main offsets.",
  },
  {
    id: "geo-comm-venezuela-sanctions-relief-oil", domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "The US grants broad sanctions relief allowing Venezuelan crude to re-enter global markets in 2026", eventClass: "sanction_decision" },
    candidate: { title: "WTI crude closes above $80/bbl at any point in the six months following the relief", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.38, pGivenAnchorFails: 0.55, strengthBand: "weak",
      counterexamples: ["Venezuela's degraded production capacity adds little incremental supply, so prices barely move and stay above $80 on other drivers"], confidence: 0.55 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Sanctions relief lets additional Venezuelan barrels reach the market, loosening supply and weighing on WTI (sign: negative). The weak band reflects uncertain incremental volume from a degraded oil sector.",
  },
  {
    id: "pol-sect-carbon-tax-coal", domain: "politics", relationType: "politics-sector",
    anchor: { title: "Congress enacts a federal carbon tax of at least $40/ton in 2027", eventClass: "legislation" },
    candidate: { title: "US thermal-coal producer Peabody Energy (BTU) ends the following year lower than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.45, strengthBand: "moderate",
      counterexamples: ["a global energy-supply crunch keeps coal demand and prices elevated, lifting Peabody even with a domestic carbon tax in place"], confidence: 0.62 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A federal carbon tax raises the cost of burning coal and accelerates utility coal retirements, pressuring coal producers (anchor-true raises candidate-true, sign: positive); a supply-driven price spike is the main offset, so moderate.",
  },
  {
    id: "pol-sect-cannabis-rescheduling", domain: "politics", relationType: "politics-sector",
    anchor: { title: "The DEA reschedules cannabis from Schedule I to Schedule III in 2026", eventClass: "regulatory_decision" },
    candidate: { title: "The US cannabis ETF (MSOS) ends 2026 up more than 25%", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.25, strengthBand: "moderate",
      counterexamples: ["rescheduling is delayed in implementation and 280E tax relief is litigated, so the sector rally fizzles despite the formal reclassification"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Rescheduling removes the punitive 280E tax burden and eases banking access for cannabis operators, a direct earnings tailwind for the sector (sign: positive); execution and litigation risk keep it moderate.",
  },
  {
    id: "pol-sect-china-evtl-tariff", domain: "politics", relationType: "politics-sector",
    anchor: { title: "The US imposes a 100% tariff on imported Chinese electric vehicles in 2026", eventClass: "trade_policy" },
    candidate: { title: "US-listed EV maker Rivian (RIVN) outperforms the S&P 500 over the following two quarters", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.4, strengthBand: "weak",
      counterexamples: ["Rivian's own production and cash-burn problems dominate the stock, so it underperforms even with Chinese competition walled off"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A steep tariff on Chinese EVs shields domestic makers from low-cost competition, a relative tailwind for US producers like Rivian (sign: positive); company-specific execution dominates the move, so weak.",
  },
  {
    id: "pol-sect-immigration-crackdown-homebuilders", domain: "politics", relationType: "politics-sector",
    anchor: { title: "The US enacts mass-deportation legislation removing 1M+ undocumented workers in 2027", eventClass: "legislation" },
    candidate: { title: "The S&P homebuilders sub-industry underperforms the S&P 500 over the following two quarters", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.42, strengthBand: "weak",
      counterexamples: ["falling mortgage rates ignite housing demand and lift homebuilders despite a tighter, costlier labor pool"], confidence: 0.52 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Removing construction labor raises homebuilders' labor costs and slows completions, pressuring the group relative to the market (sign: positive); the rate cycle dominates homebuilder returns, so weak.",
  },
  {
    id: "pol-sect-antitrust-bigtech", domain: "politics", relationType: "politics-sector",
    anchor: { title: "A US court orders a structural breakup of Google (Alphabet) in 2026", eventClass: "regulatory_decision" },
    candidate: { title: "The communication-services sector ETF (XLC) underperforms the S&P 500 over the following quarter", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.58, pGivenAnchorFails: 0.42, strengthBand: "weak",
      counterexamples: ["the market prices a breakup as value-unlocking ('sum of the parts'), so XLC rallies on the ruling instead of falling"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A forced breakup of a top XLC constituent raises antitrust overhang across big-tech platforms, a near-term drag on the sector (sign: positive); break-up-as-value-unlock is a real counter-narrative, so weak.",
  },
  {
    id: "pol-sect-ira-repeal-solar", domain: "politics", relationType: "politics-sector",
    anchor: { title: "Congress repeals the Inflation Reduction Act clean-energy tax credits in 2027", eventClass: "legislation" },
    candidate: { title: "US residential-solar installer Sunrun (RUN) ends the following year lower than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.72, pGivenAnchorFails: 0.45, strengthBand: "moderate",
      counterexamples: ["falling panel costs and lower interest rates restore residential-solar payback economics, lifting Sunrun even without the credits"], confidence: 0.62 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Repealing the IRA credits removes a core subsidy underpinning residential-solar unit economics, a direct hit to installers like Sunrun (sign: positive); cheaper hardware and rates can offset, so moderate.",
  },
  {
    id: "pol-sect-snap-medicaid-cuts-retail", domain: "politics", relationType: "politics-sector",
    anchor: { title: "Congress enacts deep cuts to SNAP and Medicaid in the 2027 budget", eventClass: "legislation" },
    candidate: { title: "US discount retailer Dollar General (DG) ends the following year lower than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.58, pGivenAnchorFails: 0.42, strengthBand: "weak",
      counterexamples: ["a trade-down dynamic in a weak economy pushes more shoppers to dollar stores, lifting Dollar General despite reduced benefits spending"], confidence: 0.52 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Cutting SNAP/Medicaid reduces disposable income for low-income consumers who are the core dollar-store customer, a demand headwind (sign: positive); recessionary trade-down can offset it, so weak.",
  },
  {
    id: "neg-ctrl-volcano-vs-taylor-album", domain: "cross", relationType: "negative-control",
    anchor: { title: "A VEI-4 or larger volcanic eruption occurs anywhere in 2026", eventClass: "natural_disaster_occurrence" },
    candidate: { title: "Taylor Swift releases a new studio album in 2026", eventClass: "media_release" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.45, pGivenAnchorFails: 0.45, strengthBand: "none",
      counterexamples: ["no shared driver between geophysical activity and a pop album schedule"], confidence: 0.94 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A volcanic eruption and an artist's release calendar share no mechanism; independent.",
  },
  {
    id: "neg-ctrl-spacex-launch-vs-wimbledon", domain: "cross", relationType: "negative-control",
    anchor: { title: "SpaceX completes 150+ orbital launches in 2026", eventClass: "launch_count_threshold" },
    candidate: { title: "A first-time men's singles champion wins Wimbledon 2026", eventClass: "tournament_winner" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.3, pGivenAnchorFails: 0.3, strengthBand: "none",
      counterexamples: ["rocket cadence and a tennis result have no causal pathway"], confidence: 0.95 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Orbital launch cadence and a tennis championship share no mechanism; independent.",
  },
  {
    id: "neg-ctrl-coffee-price-vs-gta-release", domain: "cross", relationType: "negative-control",
    anchor: { title: "Arabica coffee futures close above $4.00/lb at any point in 2026", eventClass: "commodity_price_threshold" },
    candidate: { title: "Grand Theft Auto VI ships before the end of 2026", eventClass: "product_launch" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.55, strengthBand: "none",
      counterexamples: ["coffee crop economics and a game studio's ship date are unconnected"], confidence: 0.93 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A soft-commodity price and a video-game release date share no driver; independent.",
  },
  {
    id: "neg-ctrl-papal-trip-vs-nobel-physics", domain: "cross", relationType: "negative-control",
    anchor: { title: "The Pope makes an official visit to Asia in 2026", eventClass: "official_visit" },
    candidate: { title: "The 2026 Nobel Prize in Physics goes to a quantum-computing researcher", eventClass: "award_winner" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.2, pGivenAnchorFails: 0.2, strengthBand: "none",
      counterexamples: ["a papal itinerary tells nothing about a physics-prize subfield"], confidence: 0.94 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A papal travel schedule and a Nobel committee's choice share no mechanism; independent.",
  },
  {
    id: "neg-ctrl-hurricane-count-vs-tesla-delivery", domain: "cross", relationType: "negative-control",
    anchor: { title: "The 2026 Atlantic hurricane season produces 18 or more named storms", eventClass: "weather_season_count" },
    candidate: { title: "Tesla delivers more than 2 million vehicles in 2026", eventClass: "company_metric_threshold" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.35, pGivenAnchorFails: 0.35, strengthBand: "none",
      counterexamples: ["storm counts and global EV delivery volumes have no shared cause"], confidence: 0.92 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "An Atlantic storm tally and an automaker's annual deliveries share no mechanism; independent.",
  },
  {
    id: "neg-ctrl-tiktok-ban-vs-everest-deaths", domain: "cross", relationType: "negative-control",
    anchor: { title: "A US federal TikTok ban takes legal effect in 2026", eventClass: "regulatory_action" },
    candidate: { title: "The 2026 Everest climbing season records 10 or more fatalities", eventClass: "fatality_count_threshold" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.25, pGivenAnchorFails: 0.25, strengthBand: "none",
      counterexamples: ["US app regulation and Himalayan mountaineering risk are unconnected"], confidence: 0.95 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A social-media ban and Everest season fatalities share no causal pathway; independent.",
  },
  {
    id: "neg-ctrl-mars-sample-vs-eurozone-cpi", domain: "cross", relationType: "negative-control",
    anchor: { title: "NASA announces a confirmed biosignature in returned Mars samples in 2026", eventClass: "scientific_announcement" },
    candidate: { title: "Eurozone annual CPI prints below 2% in December 2026", eventClass: "macro_metric" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.3, pGivenAnchorFails: 0.3, strengthBand: "none",
      counterexamples: ["a planetary-science finding does not move euro-area inflation"], confidence: 0.94 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A Mars biosignature announcement and eurozone inflation share no mechanism; independent.",
  },
];
