import type { AssociationRelation, AssociationDirection, MechanismType, MechanismScope } from "./types";

export interface GoldRelation {
  id: string;
  domain: string;
  relationType: string;
  anchor: { title: string; eventClass: string };
  candidate: { title: string; eventClass: string };
  label: {
    relation: AssociationRelation;
    direction: Extract<AssociationDirection, "POSITIVE" | "NEGATIVE" | "AMBIGUOUS">;
    mechanismType: MechanismType;
    scope: MechanismScope;
    pGivenAnchorWins: number;
    pGivenAnchorFails: number;
    strengthBand: "strong" | "moderate" | "weak" | "none";
    counterexamples: string[];
    confidence: number;
  };
  basis: "logical" | "causal" | "historical";
  labeledBy: "opus-4.8";
  rationale: string;
}

export const RELATION_GOLD: GoldRelation[] = [
  {
    id: "logic-btc-threshold-implication",
    domain: "crypto", relationType: "logical-implication",
    anchor: { title: "Bitcoin above $100,000 in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Bitcoin above $90,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.25, strengthBand: "strong",
      counterexamples: ["price gaps from $80k to $110k without printing $90k"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Monotonic price: hitting $100k entails having hit $90k.",
  },
  {
    id: "logic-wc-mutex-france-spain",
    domain: "sports", relationType: "logical-mutex",
    anchor: { title: "France win the 2026 World Cup", eventClass: "tournament_winner" },
    candidate: { title: "Spain win the 2026 World Cup", eventClass: "tournament_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.18, strengthBand: "strong",
      counterexamples: ["tournament cancelled / shared title (effectively impossible)"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Only one nation wins; if France wins, Spain cannot.",
  },
  {
    id: "causal-spain-star-injury",
    domain: "sports", relationType: "same-entity-causal",
    anchor: { title: "Spain win the 2026 World Cup", eventClass: "tournament_winner" },
    candidate: { title: "Spain's first-choice striker ruled out injured before the final", eventClass: "player_injury" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.05, pGivenAnchorFails: 0.18, strengthBand: "moderate",
      counterexamples: ["a deep squad wins despite the injury"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Losing a key player lowers win probability, so the injury is more likely in the fail branch.",
  },
  {
    id: "neg-control-btc-vs-oscars",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Bitcoin above $100,000 in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Oppenheimer sequel wins Best Picture 2026", eventClass: "award_winner" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.1, pGivenAnchorFails: 0.1, strengthBand: "none",
      counterexamples: ["no shared driver"], confidence: 0.9 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Crypto price and an awards outcome share no mechanism; independent.",
  },
  {
    id: "neg-control-fed-vs-lakers",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Fed cuts rates at the next FOMC meeting", eventClass: "monetary_policy_decision" },
    candidate: { title: "Los Angeles Lakers win the 2026 NBA Finals", eventClass: "tournament_winner" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.12, pGivenAnchorFails: 0.12, strengthBand: "none",
      counterexamples: ["no shared driver between monetary policy and a basketball outcome"], confidence: 0.92 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A monetary-policy decision and an NBA championship share no causal pathway; independent.",
  },
  {
    id: "neg-control-trump-approval-vs-btc",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Trump approval rating above 45% on Dec 31, 2026", eventClass: "approval_rating_threshold" },
    candidate: { title: "Bitcoin above $90,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.4, pGivenAnchorFails: 0.4, strengthBand: "none",
      counterexamples: ["no reliable shared driver; any link is weak and noisy"], confidence: 0.75 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Presidential approval and a crypto price threshold have no dependable mechanism linking them; treat as independent.",
  },

  // ── logical-implication (objective conditionals; win-branch ≈ 1) ───────────
  {
    id: "logic-eth-threshold-implication",
    domain: "crypto", relationType: "logical-implication",
    anchor: { title: "Ethereum above $6,000 in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Ethereum above $4,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.35, strengthBand: "strong",
      counterexamples: ["a flash spike from $3.9k straight to $6.1k that never prints $4k (vanishingly unlikely on a continuous tape)"], confidence: 0.97 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Same asset, monotonic threshold: clearing $6k entails having been above $4k.",
  },
  {
    id: "logic-dem-electoral-implication",
    domain: "politics", relationType: "logical-implication",
    anchor: { title: "Democrats win 300+ electoral votes in 2028", eventClass: "election_margin_threshold" },
    candidate: { title: "Democrats win the 2028 US presidential election", eventClass: "election_winner" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.0, strengthBand: "strong",
      counterexamples: ["a 269–269 tie thrown to the House (cannot reach 300 EVs and lose the presidency simultaneously)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "270 EVs wins; 300+ EVs is strictly more than 270, so the larger threshold logically entails the win.",
  },
  {
    id: "logic-temp-record-implication",
    domain: "climate", relationType: "logical-implication",
    anchor: { title: "2026 is the hottest year on record globally", eventClass: "record_threshold" },
    candidate: { title: "2026 global average temperature exceeds the 2015–2025 mean", eventClass: "metric_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.7, strengthBand: "strong",
      counterexamples: ["a dataset-definition mismatch where 'record' and the decadal-mean baseline use different reanalysis products"], confidence: 0.95 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "The all-time record exceeds every prior year, hence necessarily exceeds the recent-decade mean; the fail branch is still high because warm-but-not-record years usually beat the decadal mean too.",
  },

  // ── logical-mutex (objective conditionals; win-branch ≈ 0) ──────────────────
  {
    id: "logic-election-mutex-trump-newsom",
    domain: "politics", relationType: "logical-mutex",
    anchor: { title: "A Republican wins the 2028 US presidential election", eventClass: "election_winner" },
    candidate: { title: "A Democrat wins the 2028 US presidential election", eventClass: "election_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.92, strengthBand: "strong",
      counterexamples: ["a third-party/independent winner makes both fail simultaneously"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "One winner per election; a Republican win precludes a Democratic win. Fail-branch is high but below 1 because an independent could win.",
  },
  {
    id: "logic-mutex-fed-hike-cut",
    domain: "macro", relationType: "logical-mutex",
    anchor: { title: "The Fed raises rates at the July 2026 FOMC meeting", eventClass: "monetary_policy_decision" },
    candidate: { title: "The Fed cuts rates at the July 2026 FOMC meeting", eventClass: "monetary_policy_decision" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "SAME_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.45, strengthBand: "strong",
      counterexamples: ["the Committee holds rates unchanged, so both a hike and a cut fail at the same meeting"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A single decision at one meeting cannot be both a hike and a cut; a hold makes both fail, so the fail branch sits well under 1.",
  },
  {
    id: "logic-mutex-oscar-bestpicture",
    domain: "entertainment", relationType: "logical-mutex",
    anchor: { title: "Film A wins Best Picture at the 2027 Oscars", eventClass: "award_winner" },
    candidate: { title: "Film B wins Best Picture at the 2027 Oscars", eventClass: "award_winner" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.15, strengthBand: "strong",
      counterexamples: ["a tie is announced (Academy rules effectively preclude this for Best Picture)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Best Picture has exactly one winner; A winning means B cannot. Fail-branch low because B is only one of many nominees.",
  },

  // ── same-entity-causal (sign + mechanism + counterexample + honest band) ────
  {
    id: "causal-lakers-star-injury",
    domain: "sports", relationType: "same-entity-causal",
    anchor: { title: "Los Angeles Lakers win the 2026 NBA Finals", eventClass: "tournament_winner" },
    candidate: { title: "The Lakers' leading scorer misses 10+ playoff games injured", eventClass: "player_injury" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.07, pGivenAnchorFails: 0.22, strengthBand: "moderate",
      counterexamples: ["the bench overperforms and the team wins anyway despite the absence"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Losing the leading scorer for a chunk of the playoffs lowers title odds, so the injury concentrates in the fail branch (sign: negative).",
  },
  {
    id: "causal-incumbent-recession",
    domain: "politics", relationType: "same-entity-causal",
    anchor: { title: "The incumbent party retains the White House in 2028", eventClass: "election_winner" },
    candidate: { title: "The US enters a recession (two consecutive negative-GDP quarters) in 2027–2028", eventClass: "macro_recession" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "CAUSAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.12, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["a brief early recession that recovers well before election day (1984-style), so the incumbent still wins"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Recessions hurt incumbents via economic-voting; a recession is therefore more likely in the branch where the incumbent loses (sign: negative). Timing of recovery is the main confounder, hence moderate.",
  },
  {
    id: "causal-tesla-deliveries-record",
    domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Tesla stock closes above $400 at end of 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Tesla reports a record quarterly delivery number in 2026", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["record deliveries at collapsing margins drag the stock down despite the volume beat"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Record deliveries are a fundamental tailwind that supports a higher share price, so they cluster in the win branch (sign: positive). Margins/valuation can break the link, so only moderate.",
  },

  // ── cross-entity (one entity's outcome shifts another's; sign + mechanism) ──
  {
    id: "cross-entity-opec-cut-exxon",
    domain: "commodities", relationType: "cross-entity",
    anchor: { title: "OPEC+ announces a production cut in H2 2026", eventClass: "supply_decision" },
    candidate: { title: "ExxonMobil stock closes above $130 at end of 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.35, strengthBand: "moderate",
      counterexamples: ["non-OPEC supply (US shale) floods the market and offsets the cut, so crude and Exxon fall anyway"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "An OPEC+ cut props up crude, lifting integrated-oil earnings and Exxon's stock — a cross-entity channel via the oil price (sign: positive). Offsetting supply is the key confounder.",
  },
  {
    id: "cross-entity-nvidia-tsmc",
    domain: "equities", relationType: "cross-entity",
    anchor: { title: "Nvidia reports a record data-center revenue quarter in 2026", eventClass: "earnings_metric" },
    candidate: { title: "TSMC reports year-over-year revenue growth above 25% in 2026", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["TSMC's other segments (auto, smartphone) slump enough to mask strong AI-chip demand"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Nvidia is a top TSMC customer; a record Nvidia data-center quarter means heavy leading-edge wafer orders, pulling TSMC revenue up (supplier channel, sign: positive).",
  },
  {
    id: "cross-entity-ukraine-ceasefire-defense",
    domain: "geopolitics", relationType: "cross-entity",
    anchor: { title: "A durable Russia–Ukraine ceasefire holds for 90+ days in 2026", eventClass: "conflict_resolution" },
    candidate: { title: "Lockheed Martin stock closes above $500 at end of 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.4, pGivenAnchorFails: 0.55, strengthBand: "weak",
      counterexamples: ["European rearmament and Pacific tensions keep defense backlogs full regardless of a Ukraine ceasefire"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A ceasefire trims the most visible demand catalyst for defense primes, mildly pressuring Lockheed (sign: negative) — but multi-year backlogs and other theaters dominate, so the link is weak.",
  },

  // ── macro-chain (macro variable → downstream market; sign + mechanism) ──────
  {
    id: "macro-chain-fed-cut-housing",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "The Fed cuts rates by 75+ bps cumulatively in 2026", eventClass: "monetary_policy_path" },
    candidate: { title: "US 30-year mortgage rate falls below 6% at any point in 2026", eventClass: "rate_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.7, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["term premium / MBS spreads widen so long rates stay high even as the Fed cuts the front end"], confidence: 0.65 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Front-end cuts pass partly into long rates and mortgage pricing, raising the chance the 30-year dips below 6% (sign: positive). The curve/spread can decouple, so moderate.",
  },
  {
    id: "macro-chain-inflation-gold",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "US CPI prints above 4% year-over-year in any month of 2026", eventClass: "inflation_threshold" },
    candidate: { title: "Gold closes above $3,000/oz at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.65, pGivenAnchorFails: 0.45, strengthBand: "weak",
      counterexamples: ["the Fed hikes aggressively into the inflation, real yields spike, and gold falls despite high CPI"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Higher inflation supports gold as an inflation hedge (sign: positive), but the dominant driver is real yields — a hawkish reaction can flip the relationship — so only weak.",
  },
  {
    id: "macro-chain-dollar-emerging",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "The US Dollar Index (DXY) rises above 110 at any point in 2026", eventClass: "fx_threshold" },
    candidate: { title: "The MSCI Emerging Markets index ends 2026 lower than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["a strong-dollar driven by US growth that simultaneously lifts EM exporters' earnings"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A strong dollar tightens EM financial conditions (dollar debt, capital outflows), raising the chance EM equities fall (anchor-true ↑ candidate-true). 'Why' the dollar is strong is the confounder.",
  },

  // ── geopolitics-commodity (conflict/supply shock → commodity price) ─────────
  {
    id: "geo-commodity-hormuz-oil",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "A military closure or blockade of the Strait of Hormuz occurs in 2026", eventClass: "supply_shock" },
    candidate: { title: "Brent crude closes above $120/bbl at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.9, pGivenAnchorFails: 0.15, strengthBand: "strong",
      counterexamples: ["a coordinated SPR release plus rapid de-escalation caps the spike below $120"], confidence: 0.8 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "~20% of seaborne oil transits Hormuz; a closure is a direct, large supply shock that almost always spikes Brent (sign: positive, strong). Reserve releases only partly offset.",
  },
  {
    id: "geo-commodity-russia-sanctions-gas",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "The EU imposes a full embargo on Russian pipeline gas in 2026", eventClass: "sanction_decision" },
    candidate: { title: "European TTF natural gas closes above €60/MWh at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.85, pGivenAnchorFails: 0.4, strengthBand: "strong",
      counterexamples: ["a mild winter plus full LNG import terminals keep storage high and prices contained"], confidence: 0.75 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Removing Russian pipeline gas tightens European supply and lifts TTF (sign: positive). Weather and LNG availability are the main offsets, but the directional push is strong.",
  },
  {
    id: "geo-commodity-blacksea-wheat",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "The Black Sea grain corridor is shut for 60+ consecutive days in 2026", eventClass: "supply_shock" },
    candidate: { title: "Chicago wheat futures close above $8.00/bushel at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.75, pGivenAnchorFails: 0.3, strengthBand: "moderate",
      counterexamples: ["a bumper harvest in the US, EU and Australia replaces the lost Black Sea tonnage"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Ukraine/Russia are major wheat exporters; a prolonged corridor shutdown removes supply and pushes wheat up (sign: positive). Competing-region harvests can blunt it, hence moderate.",
  },

  // ── politics-sector (policy/election outcome → sector or asset) ─────────────
  {
    id: "politics-sector-gop-energy",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Republicans control both chambers of Congress after the 2026 midterms", eventClass: "election_winner" },
    candidate: { title: "The S&P 500 Energy sector (XLE) ends 2026 higher than the broad index", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.4, strengthBand: "weak",
      counterexamples: ["a collapse in the oil price overwhelms any policy tailwind, so energy underperforms despite favorable politics"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "GOP control favors looser drilling/permitting policy that modestly supports energy names (sign: positive), but the commodity cycle dominates sector returns, so the policy signal is weak.",
  },
  {
    id: "politics-sector-dem-renewables",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Democrats win the 2028 US presidential election", eventClass: "election_winner" },
    candidate: { title: "The clean-energy ETF (ICLN) ends 2028 up more than 20%", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.45, pGivenAnchorFails: 0.25, strengthBand: "weak",
      counterexamples: ["high interest rates crush long-duration clean-energy valuations regardless of supportive policy"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Democratic control is associated with subsidies/tax credits for renewables, a tailwind for ICLN (sign: positive). Rates and subsidy timing dominate, so the relationship is weak.",
  },
  {
    id: "politics-sector-tariff-industrials",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "The US imposes new broad tariffs above 20% on Chinese goods in 2026", eventClass: "trade_policy" },
    candidate: { title: "US-listed Chinese ADRs (KWEB) end 2026 lower than they started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.65, pGivenAnchorFails: 0.45, strengthBand: "moderate",
      counterexamples: ["aggressive Chinese stimulus offsets the tariff hit and lifts the ADRs anyway"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "New broad tariffs hurt Chinese-economy-exposed equities, raising the chance KWEB falls (anchor-true ↑ candidate-true, sign: positive). Domestic stimulus is the main counterforce.",
  },

  // ── extra negative-controls (independent / AMBIGUOUS) ───────────────────────
  {
    id: "neg-control-eurovision-vs-gdp",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "Sweden wins the 2026 Eurovision Song Contest", eventClass: "award_winner" },
    candidate: { title: "US Q3 2026 GDP growth exceeds 3% annualized", eventClass: "macro_metric" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.25, pGivenAnchorFails: 0.25, strengthBand: "none",
      counterexamples: ["no plausible shared driver between a song contest and US output"], confidence: 0.93 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A European song-contest result and US GDP have no mechanism linking them; independent.",
  },
  {
    id: "neg-control-superbowl-vs-btc",
    domain: "cross", relationType: "negative-control",
    anchor: { title: "An AFC team wins Super Bowl LXI", eventClass: "tournament_winner" },
    candidate: { title: "Bitcoin above $100,000 in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "UNRELATED", direction: "AMBIGUOUS", mechanismType: "OTHER", scope: "CROSS_DOMAIN",
      pGivenAnchorWins: 0.5, pGivenAnchorFails: 0.5, strengthBand: "none",
      counterexamples: ["the 'Super Bowl indicator' is a debunked spurious correlation, not a mechanism"], confidence: 0.9 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Which conference wins the Super Bowl carries no causal information about Bitcoin's price; treat as independent.",
  },

  // ── batch 2: more coverage (≥5 per bucket where it sharpens the signal) ─────

  // logical-implication
  {
    id: "logic-sp500-threshold-implication",
    domain: "equities", relationType: "logical-implication",
    anchor: { title: "The S&P 500 closes above 7,000 at any point in 2026", eventClass: "index_threshold" },
    candidate: { title: "The S&P 500 closes above 6,500 at any point in 2026", eventClass: "index_threshold" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.55, strengthBand: "strong",
      counterexamples: ["an overnight gap open from 6,400 straight through 7,000 that never closes at 6,500 (rare on daily-close resolution)"], confidence: 0.96 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "Same index, nested thresholds: closing above 7,000 entails the index has been above 6,500. Fail-branch high because 6,500 is reachable without 7,000.",
  },
  {
    id: "logic-gop-senate-seats-implication",
    domain: "politics", relationType: "logical-implication",
    anchor: { title: "Republicans hold 55+ Senate seats after the 2026 midterms", eventClass: "election_margin_threshold" },
    candidate: { title: "Republicans hold a Senate majority after the 2026 midterms", eventClass: "election_winner" },
    label: { relation: "IMPLICATION", direction: "POSITIVE", mechanismType: "IMPLICATION", scope: "SAME_ENTITY",
      pGivenAnchorWins: 1.0, pGivenAnchorFails: 0.4, strengthBand: "strong",
      counterexamples: ["redefinition of 'majority' via an independent caucusing arrangement (does not change the 55>50 arithmetic)"], confidence: 0.98 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "55 seats exceeds the 51 needed for a majority, so the larger count logically entails the majority.",
  },

  // logical-mutex
  {
    id: "logic-mutex-recession-no-recession",
    domain: "macro", relationType: "logical-mutex",
    anchor: { title: "The US is officially in recession (NBER) for all of Q2 2026", eventClass: "macro_recession" },
    candidate: { title: "US real GDP grows in Q2 2026", eventClass: "macro_metric" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "SAME_ENTITY",
      pGivenAnchorWins: 0.05, pGivenAnchorFails: 0.7, strengthBand: "strong",
      counterexamples: ["a quarter with positive headline GDP that NBER still dates as recessionary on employment/income (definitional edge case)"], confidence: 0.9 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A full quarter of recession and positive same-quarter growth are near-mutually-exclusive; small residual because NBER dating is multi-indicator, not GDP-only.",
  },
  {
    id: "logic-mutex-champion-relegated",
    domain: "sports", relationType: "logical-mutex",
    anchor: { title: "Manchester City win the 2026–27 Premier League title", eventClass: "tournament_winner" },
    candidate: { title: "Manchester City are relegated from the Premier League in 2026–27", eventClass: "league_outcome" },
    label: { relation: "MUTEX", direction: "NEGATIVE", mechanismType: "LOGICAL", scope: "SAME_ENTITY",
      pGivenAnchorWins: 0.0, pGivenAnchorFails: 0.02, strengthBand: "strong",
      counterexamples: ["a mid-season points deduction theoretically separating on-pitch finish from final standing (cannot make a champion finish bottom three)"], confidence: 0.99 },
    basis: "logical", labeledBy: "opus-4.8",
    rationale: "A team cannot both finish 1st and finish in the relegation zone in the same season; finishing positions are a single total order.",
  },

  // same-entity-causal
  {
    id: "causal-airline-fuel-margin",
    domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Delta Air Lines reports a record annual profit for 2026", eventClass: "earnings_metric" },
    candidate: { title: "The average jet-fuel price in 2026 is higher than in 2025", eventClass: "input_cost" },
    label: { relation: "CAUSAL", direction: "NEGATIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.3, pGivenAnchorFails: 0.5, strengthBand: "moderate",
      counterexamples: ["strong fare/demand pricing power lets Delta post record profit even with fuel up (hedging + capacity discipline)"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Fuel is a top airline cost; higher fuel pressures margins, so record profit is less likely when fuel rises (sign: negative). Pricing power and hedges weaken the link.",
  },
  {
    id: "causal-streamer-subs-stock",
    domain: "equities", relationType: "same-entity-causal",
    anchor: { title: "Netflix stock closes at an all-time high in 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "Netflix adds 30M+ net new subscribers in 2026", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "ENTITY_SPECIFIC",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.25, strengthBand: "moderate",
      counterexamples: ["the market rewards ARPU/ads monetization over raw sub growth, so the stock peaks on a softer add number"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Strong subscriber growth is a fundamental driver of Netflix's valuation, so a big add number clusters with the all-time-high branch (sign: positive). Monetization mix can substitute for raw adds.",
  },

  // cross-entity
  {
    id: "cross-entity-apple-iphone-tsmc",
    domain: "equities", relationType: "cross-entity",
    anchor: { title: "Apple reports record iPhone unit shipments for the 2026 holiday quarter", eventClass: "earnings_metric" },
    candidate: { title: "TSMC reports record advanced-node (3nm/2nm) revenue in early 2027", eventClass: "earnings_metric" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.65, pGivenAnchorFails: 0.45, strengthBand: "moderate",
      counterexamples: ["Apple front-loaded wafer orders in a prior quarter, decoupling the holiday-quarter shipment from TSMC's reported timing"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Apple is TSMC's largest leading-edge customer; a record iPhone quarter implies heavy advanced-node demand, lifting TSMC (supplier channel, sign: positive). Order-timing lag is the confounder.",
  },
  {
    id: "cross-entity-saudi-aramco-tax",
    domain: "geopolitics", relationType: "cross-entity",
    anchor: { title: "Saudi Arabia commits to extended deep OPEC+ output cuts through 2027", eventClass: "supply_decision" },
    candidate: { title: "US shale producer Diamondback Energy raises its 2027 capex guidance", eventClass: "corporate_guidance" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "CROSS_ENTITY",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.35, strengthBand: "weak",
      counterexamples: ["US shale stays disciplined on capital returns and keeps capex flat despite higher prices"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Saudi cuts support crude, improving US shale economics and inviting more capex — a cross-entity price channel (sign: positive). Capital-discipline norms make it weak.",
  },

  // macro-chain
  {
    id: "macro-chain-rate-cut-regional-banks",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "The Fed cuts rates at three or more meetings in 2026", eventClass: "monetary_policy_path" },
    candidate: { title: "The regional-bank ETF (KRE) ends 2026 higher than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "weak",
      counterexamples: ["cuts come because of a recession that drives loan losses, so regional banks fall even as the Fed eases"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Cuts relieve funding costs and CRE stress for regional banks (sign: positive), but if cuts are recession-driven, credit losses dominate — a classic 'why are they cutting' confounder, hence weak.",
  },
  {
    id: "macro-chain-oil-airlines",
    domain: "macro", relationType: "macro-chain",
    anchor: { title: "WTI crude averages above $90/bbl over 2026", eventClass: "asset_price_threshold" },
    candidate: { title: "The US airline ETF (JETS) ends 2026 lower than it started", eventClass: "index_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["robust travel demand lets carriers pass fuel costs into fares, so JETS rises despite expensive oil"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Sustained high oil raises airlines' largest variable cost, pressuring the group (anchor-true ↑ candidate-true, sign: positive). Demand-driven pricing power is the offset.",
  },

  // geopolitics-commodity
  {
    id: "geo-commodity-taiwan-tensions-chips",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "China imposes a naval quarantine or blockade around Taiwan in 2026", eventClass: "supply_shock" },
    candidate: { title: "Spot DRAM/NAND memory contract prices rise more than 30% within a quarter in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.85, pGivenAnchorFails: 0.2, strengthBand: "strong",
      counterexamples: ["a glut of existing memory inventory cushions the immediate price reaction"], confidence: 0.75 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A Taiwan blockade threatens the world's leading-edge logic and feeds memory-supply panic; semiconductor prices spike (sign: positive, strong). Inventory buffers only partly absorb the shock.",
  },
  {
    id: "geo-commodity-congo-cobalt",
    domain: "geopolitics", relationType: "geopolitics-commodity",
    anchor: { title: "An export ban or major conflict disrupts DRC cobalt mining for 30+ days in 2026", eventClass: "supply_shock" },
    candidate: { title: "Cobalt prices rise above $40,000/tonne at any point in 2026", eventClass: "asset_price_threshold" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "ECONOMIC", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.8, pGivenAnchorFails: 0.25, strengthBand: "strong",
      counterexamples: ["weak EV-battery demand and Indonesian nickel-cobalt substitution cap the price despite the DRC disruption"], confidence: 0.7 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "The DRC supplies the majority of mined cobalt; a sustained disruption is a direct supply shock that lifts cobalt (sign: positive). Demand softness and substitutes can blunt it.",
  },

  // politics-sector
  {
    id: "politics-sector-drug-pricing-pharma",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Congress passes expanded Medicare drug-price negotiation in 2026", eventClass: "legislation" },
    candidate: { title: "The S&P pharma sub-industry underperforms the S&P 500 over the following quarter", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.6, pGivenAnchorFails: 0.4, strengthBand: "moderate",
      counterexamples: ["the bill is milder than feared and triggers a relief rally in pharma"], confidence: 0.6 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "Expanded price negotiation compresses pharma pricing power, pressuring the group relative to the market (anchor-true ↑ candidate-true, sign: positive). 'Better than feared' outcomes are the main risk to the sign.",
  },
  {
    id: "politics-sector-defense-budget",
    domain: "politics", relationType: "politics-sector",
    anchor: { title: "Congress enacts a defense budget above $950B for FY2027", eventClass: "legislation" },
    candidate: { title: "The aerospace & defense ETF (ITA) outperforms the S&P 500 over the following two quarters", eventClass: "relative_return" },
    label: { relation: "CAUSAL", direction: "POSITIVE", mechanismType: "INSTITUTIONAL", scope: "EVENT_GLOBAL",
      pGivenAnchorWins: 0.55, pGivenAnchorFails: 0.4, strengthBand: "weak",
      counterexamples: ["the budget is already priced in, so the enactment is a 'sell-the-news' event for defense names"], confidence: 0.5 },
    basis: "causal", labeledBy: "opus-4.8",
    rationale: "A larger defense budget supports prime-contractor backlogs and defense equities (sign: positive), but expectations are usually pre-positioned, so the realized relative move is weak.",
  },
];
